### ISSUE TITLE
SBR API

### ISSUE THREAD

**Issue by daniel1596** [SharpChiCity/SBRscraper#12]
Question for you, SharpChiCity - how did you find out about the SBR API? (I know this isn't an issue per se, and I'm happy to close/delete it soon, but I was really curious.)

**Comment by matthew-hoty** [comment]
Would love to know the answer to this as well! The API link looks pretty crazy.  Would love more details on it

**Comment by SharpChiCity** [comment]
This is the first site I found via google. There are plenty more out there, but it's straightforward
https://web.archive.org/web/20190124124750/http://www.gregreda.com/2015/02/15/web-scraping-finding-the-api/
