### ISSUE TITLE
SBR Redirect

### ISSUE THREAD

**Issue by SnarkaShark** [SharpChiCity/SBRscraper#5]
Hi, 

I'm getting an interesting issue where SBR will always redirect to a page that does not have the betting odds or OddsGridModule_3. Instead, it's hitting this page: http://imgur.com/6HFm1eV.

Any idea how or why it's redirecting me? This happens sometimes too when I just throw the url in FF. It will also change the url from 
http://www.sportsbookreview.com/betting-odds/mlb-baseball/?date=20160406

to:

http://www.sportsbookreview.com/betting-odds/mlb-baseball/?date=20160406&

Thanks for the help!

Mike

**Comment by SharpChiCity** [comment]
Can't believe I missed this. I'm fairly certain that page is when there is no game data for that day. Are you still seeing the issue?

**Comment by SharpChiCity** [comment]
going to close this out as I believe the issue was states in the above comment.
