### ISSUE TITLE
Small error leading to last column not having a header

### ISSUE THREAD

**Issue by jpw82** [SharpChiCity/SBRscraper#6]
Minor error that has a major effect on the output.

On line 407 

f.write('Game_ID,Date,Time_FG_ML,HA,Team,Team_SP,Team_SP_hand,Opp,Opp_SP,Opp_SP_hand)
you are missing a comma "," at the end of Opp_SP_hand which is causing this header to merge with the next header on line 408 and therefore all the columns after this one are off by one and shifted to the left.

**Comment by jpw82** [comment]
This was in regards to the Closing Line/Line Movement script

**Comment by SharpChiCity** [comment]
Will be updating the files shortly, but thanks for the heads up
